### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by courtneyklatt** [courtneyklatt/Presentation-Checklist#1]
[] Research Github
[] Interview Sam Matthews
[] Watch video tutorials 
[] Outline presentation
[] Develop Slideshow
[] Create speaker notes
[]Rehearse presentation

**Comment by courtneyklatt** [comment]
@mapsam Please provide your thoughts on this checklist. Would you make any additions?

**Comment by mapsam** [comment]
Looking great, @courtneyklatt!
